service: serverless-crud

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-southeast-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: readings
          method: post
          cors: true
  readAll:
    handler: handler.readAll
    events:
      - http:
          path: readings
          method: get
          cors: true
  readOne:
    handler: handler.readOne
    events:
      - http:
          path: readings/{id}
          method: get
          cors: true


  update:
    handler: handler.update
    events:
      - http:
          path: readings/{id}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: readings/{id}
          method: delete
          cors: true

resources:
  Resources:
    ReadingsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: sensor_id
            AttributeType: S
          - 
            AttributeName: published_at
            AttributeType: N

        KeySchema:
          -
            AttributeName: sensor_id
            KeyType: HASH
          -  
            AttributeName: published_at
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: 'readings'
