service: serverless-crud

provider:
  name: aws
  runtime: nodejs4.3
  region: ap-southeast-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:*"

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: readings
          method: post
          cors: true

  readEntireTable:
    handler: handler.readEntireTable
    memory: 512
    timeout: 10
    events:
      - http:
          path: readings
          method: get
          cors: true

  readAllOf:
    handler: handler.readAllOf
    memory: 512
    timeout: 5
    events:
      - http:
          path: readings/{sensor_id}
          method: get
          cors: true

  readOne:
    handler: handler.readOne
    events:
      - http:
          path: readings/{sensor_id}/{published_at}
          method: get
          cors: true
          parameters:
            paths:
              sensor_id: true
              published_at: true

  readSince:
    handler: handler.readSince
    events:
      - http:
          path: readings/{sensor_id}/{published_at}
          method: get
          cors: true

  update:
    handler: handler.update
    events:
      - http:
          path: readings/{sensor_id}/{published_at}
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: readings/{sensor_id}/{published_at}
          method: delete
          cors: true

resources:
  Resources:
    ReadingsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: sensor_id
            AttributeType: S
          - 
            AttributeName: published_at
            AttributeType: N

        KeySchema:
          -
            AttributeName: sensor_id
            KeyType: HASH
          -  
            AttributeName: published_at
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: 'readings'
